name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main, dev]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: false      # instala en la env del runner
          virtualenvs-in-project: false
          installer-parallel: true

      - name: Install dependencies (main + dev)
        run: poetry install --no-interaction --with dev

      - name: Lint con ruff
        run: poetry run ruff .

      - name: Comprobación de formato con black
        run: poetry run black --check .

      - name: Tests (pytest -q)
        run: poetry run pytest -q
